services:
  - type: web
    name: naturalnikhaar-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn ecommerce.wsgi:application --log-file=-
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "naturalnikhaar-web.onrender.com"
      - key: DJANGO_SERVE_MEDIA
        value: "True"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
